### PR TITLE
Applied fixes from StyleCI

### PR DESCRIPTION
**Pull request by sstok**
This pull request applies code style fixes from an analysis carried out by [StyleCI](https://styleci.io).

---

For more information, click [here](https://styleci.io/analyses/qyY4Nq).

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Hmmm. Sorry about that. StyleCI created this PR using the wrong user. It was meant to use my account to send this PR. Ping @sstok.

**Comment by GrahamCampbell** [comment]
Actually, this looks broken anyway. You need to disable the psr0 fixer as it's breaking the namespaces in the tests.

**Comment by sstok** [comment]
Whoops the - short_array_syntax needed to commented :)

**Comment by GrahamCampbell** [comment]
This PR needs closing please.

**Pull request closed without merging**
